// Public model cards and commit histories checked 2026-09-06. No live metrics.
export const openModels = [
  {
    id: '0dAI-7B',
    family: 0,
    title: '0dAI 7B',
    base: 'Mistral',
    format: 'BF16',
    date: '02.2024',
    es: 'Mi primera publicación de esta familia: fine-tuning de Mistral para ciberseguridad, con los pesos disponibles en Hugging Face.',
    en: 'My first release in this family: a Mistral fine-tune for cybersecurity, with weights available on Hugging Face.',
  },
  {
    id: '0dAI-7.5B-v2',
    family: 1,
    title: '0dAI 7.5B v2',
    base: 'Mistral',
    format: 'BF16',
    date: '03.2024',
    es: 'La siguiente versión incorpora trabajo con DPO y limpieza de datos. Una iteración sobre el modelo y sobre la calidad del material de entrenamiento.',
    en: 'The next version incorporates DPO and data cleaning: an iteration on both the model and the quality of its training material.',
  },
  {
    id: '0dAI-7.5B-v2-4bpw',
    family: 1,
    title: '0dAI v2 · 4 bpw',
    base: 'Mistral',
    format: 'EXL2 · 4 bpw',
    date: '03.2024',
    es: 'Una variante cuantizada de v2. Parte del trabajo de llevar el modelo a formatos con un menor coste de memoria.',
    en: 'A quantized variant of v2, part of making the model available in formats with a lower memory footprint.',
  },
  {
    id: '0dAI-7.5b-v2-8bpw',
    family: 1,
    title: '0dAI v2 · 8 bpw',
    base: 'Mistral',
    format: 'EXL2 · 8 bpw',
    date: '03.2024',
    es: 'Otra precisión de la misma familia: una publicación a 8 bits por peso que acompaña a las versiones de v2.',
    en: 'Another precision in the same family: an eight-bits-per-weight release alongside the other v2 versions.',
  },
  {
    id: '0dAI-8x7b-0761',
    family: 2,
    title: '0dAI 8×7B',
    base: 'Mixtral · MoE',
    format: 'EXL2',
    date: '06.2024',
    es: 'El recorrido continúa con una arquitectura de mezcla de expertos basada en Mixtral 8×7B y una nueva publicación de pesos.',
    en: 'The work continues with a mixture-of-experts architecture based on Mixtral 8×7B and a new weights release.',
  },
];
