export const portraits = [
  {
    year: '2023',
    label: 'La Jaula del N00b',
    detail: 'Una conversación',
    src: '/portraits/jaula-2023.jpg',
    width: 1920,
    height: 1080,
    crop: 'jaula',
    alt: 'Luis durante su conversación en La Jaula del N00b, publicada en 2023.',
    source: 'https://www.youtube.com/watch?v=aDYTheB_ejs&t=92s',
  },
  {
    year: '2024',
    label: 'AiBirras, Granada',
    detail: 'Sobre el escenario',
    src: '/portraits/aibirras-2024.jpg',
    width: 2048,
    height: 1365,
    crop: 'aibirras',
    alt: 'Luis dando una charla en AiBirras, Granada, en noviembre de 2024.',
    source: 'https://aibirras.org/events/aibirras-4-talk',
  },
  {
    year: '2025',
    label: 'IES Virgen del Carmen',
    detail: 'Compartir lo aprendido',
    src: '/portraits/ies-2025.jpg',
    width: 1536,
    height: 2048,
    crop: 'ies',
    alt: 'Luis en su sesión con estudiantes del IES Virgen del Carmen, en mayo de 2025.',
    source:
      'https://www.iesvirgendelcarmen.com/charla-pentesting-curso-de-especializacion-en-ciberseguridad-y-asir/',
  },
  {
    year: '2026',
    label: 'Por aquí, Luija.',
    detail: 'Perfil actual',
    src: '/portraits/x-current.jpg',
    width: 400,
    height: 400,
    crop: 'current',
    alt: 'Retrato actual del perfil de Luis en X, consultado en septiembre de 2026.',
    source: 'https://x.com/luijait_/photo',
  },
];
